### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by mpontus** [moscow-freecodecamp/fluffy-spoon#3]
Document existing API methods:

* `POST /auth/registration` user registration
* `POST /auth/login` user authentication
* `POST /auth/reset` request password reset
* `POST /auth/reset/:token` reset password
* `GET /verify/:user_id/:token` verify email
* `GET /users` list profiles

Document future API methods:

* `PATCH /users/:id` update profile

Documentation may be in form of integration tests.

**Comment by troglotit** [comment]
I'm not sure if auth should happen on the API level. 
I thought we're going to use JWT which means we have to pass those tokens with every API call.
Or maybe those methods are about our business logic? Like "Yeah, Susan is logged on right now"?

**Comment by mpontus** [comment]
It can't be anything but API. By authenticating you are creating an instance of JWT token resource.

**Comment by troglotit** [comment]
But I think we shouldn't persist tokens on server, just create and send to the client
