### ISSUE TITLE
Switch technology stack to MERN

### ISSUE THREAD

**Issue by w96k** [moscow-freecodecamp/fluffy-spoon#5]
I think would be better to everyone to use MERN (Mongo, Express, React, Node) stack. These technologies have tutorials on FreeCodeCamp, Vue and Postgres doesn't have. I don't want to say, that these technologies worse, just MERN would be easier for learning. 

http://mern.io
What do you think?

**Comment by w96k** [comment]
Made pull request: https://github.com/moscow-freecodecamp/fluffy-spoon/pull/6

**Comment by w96k** [comment]
I discussed a bit with @mpontus and we think that would be even better to start with just express and include stuff on the go.

**Comment by troglotit** [comment]
As we discussed with @mpontus, we agreed on MERN stack. Closing.
